package com.example.mindmingle.entities;

public enum TypePost {

        DEPRESSION,
        ANXIETE,
        TROUBLES_BIPOLAIRES,
        SCHIZOPHRENIE,
        TROUBLES_ALIMENTAIRES,
        TROUBLES_PERSONNALITE,
        TROUBLE_OBSESSIONNEL_COMPULSIF,
        TSPT,
        TROUBLES_AUTISTIQUES,
        TROUBLES_HUMEUR,
        ADDICTIONS,
        TROUBLES_SOMMEIL,
        TDAH,
        TROUBLES_DISSOCIATIFS,
        TROUBLES_PERSONNALITE_MULTIPLES,
        TROUBLES_COMPORTEMENT_ALIMENTAIRE,
        PHOBIES_SPECIFIQUES,
        TROUBLES_CONTROLE_IMPULSIONS,
        TROUBLES_LANGAGE_COMMUNICATION,
        TROUBLES_MEMOIRE



}
